-- Create form_config table if not exists
CREATE TABLE IF NOT EXISTS form_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name TEXT NOT NULL UNIQUE,
    field_label TEXT NOT NULL,
    field_type TEXT NOT NULL, -- text, number, tel, date, select, textarea
    options TEXT[] DEFAULT NULL, -- for select
    is_required BOOLEAN DEFAULT TRUE,
    order_index INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE form_config ENABLE ROW LEVEL SECURITY;

-- Policies for form_config
DROP POLICY IF EXISTS "Public Read Form Config" ON form_config;
CREATE POLICY "Public Read Form Config" ON form_config FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Form Config" ON form_config;
CREATE POLICY "Admin All Form Config" ON form_config FOR ALL USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
);

-- Seed defaults for form_config (only if empty)
INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'nisn', 'NISN', 'number', NULL, true, 1
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'nisn');

INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'full_name', 'Nama Lengkap', 'text', NULL, true, 2
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'full_name');

INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'birth_place', 'Tempat Lahir', 'text', NULL, true, 3
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'birth_place');

INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'birth_date', 'Tanggal Lahir', 'date', NULL, true, 4
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'birth_date');

INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'gender', 'Jenis Kelamin', 'select', ARRAY['Laki-laki', 'Perempuan'], true, 5
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'gender');

INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'origin_school', 'Asal Sekolah', 'text', NULL, true, 6
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'origin_school');

INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'address', 'Alamat Lengkap', 'textarea', NULL, true, 7
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'address');

INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'parent_name', 'Nama Orang Tua/Wali', 'text', NULL, true, 8
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'parent_name');

INSERT INTO form_config (field_name, field_label, field_type, options, is_required, order_index)
SELECT 'parent_phone', 'No HP Orang Tua', 'tel', NULL, true, 9
WHERE NOT EXISTS (SELECT 1 FROM form_config WHERE field_name = 'parent_phone');


-- Create document_config table
CREATE TABLE IF NOT EXISTS document_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type TEXT NOT NULL UNIQUE, -- used as ID in code (e.g. 'kk', 'akta')
    label TEXT NOT NULL,
    is_required BOOLEAN DEFAULT TRUE,
    order_index INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE document_config ENABLE ROW LEVEL SECURITY;

-- Policies for document_config
DROP POLICY IF EXISTS "Public Read Doc Config" ON document_config;
CREATE POLICY "Public Read Doc Config" ON document_config FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Doc Config" ON document_config;
CREATE POLICY "Admin All Doc Config" ON document_config FOR ALL USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
);

-- Seed defaults for document_config
INSERT INTO document_config (document_type, label, is_required, order_index)
SELECT 'kk', 'Kartu Keluarga (KK)', true, 1
WHERE NOT EXISTS (SELECT 1 FROM document_config WHERE document_type = 'kk');

INSERT INTO document_config (document_type, label, is_required, order_index)
SELECT 'akta', 'Akta Kelahiran', true, 2
WHERE NOT EXISTS (SELECT 1 FROM document_config WHERE document_type = 'akta');

INSERT INTO document_config (document_type, label, is_required, order_index)
SELECT 'ijazah', 'Ijazah / SKL (Jika ada)', false, 3
WHERE NOT EXISTS (SELECT 1 FROM document_config WHERE document_type = 'ijazah');

INSERT INTO document_config (document_type, label, is_required, order_index)
SELECT 'foto', 'Pas Foto 3x4', true, 4
WHERE NOT EXISTS (SELECT 1 FROM document_config WHERE document_type = 'foto');
