-- 1. Add 'track' to registrations
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS track TEXT;
-- Constraint to ensure valid tracks
ALTER TABLE registrations DROP CONSTRAINT IF EXISTS valid_track;
ALTER TABLE registrations ADD CONSTRAINT valid_track CHECK (track IN ('fullday_ikhwan', 'fullday_akhwat', 'boarding_ikhwan', 'boarding_akhwat'));

-- 2. Create document_templates table
CREATE TABLE IF NOT EXISTS document_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content_html TEXT NOT NULL, -- Rich Text content
    target_tracks TEXT[] DEFAULT NULL, -- Array of tracks this doc applies to. NULL = All.
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for document_templates
ALTER TABLE document_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Templates" ON document_templates FOR SELECT USING (true);
CREATE POLICY "Admin Manage Templates" ON document_templates FOR ALL USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
);

-- 3. generated_documents (To link generated PDFs to templates, optional but good for tracking)
CREATE TABLE IF NOT EXISTS generated_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id UUID REFERENCES registrations(id) ON DELETE CASCADE,
    template_id BIGINT REFERENCES document_templates(id),
    file_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE generated_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own generated docs" ON generated_documents FOR SELECT USING (auth.uid() = registration_id);
CREATE POLICY "Users insert own generated docs" ON generated_documents FOR INSERT WITH CHECK (auth.uid() = registration_id);
